# -*- coding: utf-8 -*-
import json
import logging
import requests
from datetime import date, timedelta

from odoo import api, fields, models, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

GEMINI_BASE = 'https://generativelanguage.googleapis.com'


class IncidentReportAI(models.Model):
    """AI-powered corrective action recommendations for incident reports."""
    _inherit = 'incident.report'

    ai_recommendations_generated = fields.Boolean(
        'AI Recommendations Generated', default=False, copy=False,
        help='Set when AI recommendations have been generated for this incident.')

    # ── Public action — called from button ─────────────────────────────────
    def action_ai_recommend_corrective_actions(self):
        """Call the configured AI provider to recommend corrective actions."""
        self.ensure_one()

        provider, api_key = self._get_ai_provider()
        context_text = self._build_incident_context()

        if provider == 'openai':
            raw_json = self._call_openai(api_key, context_text)
        else:
            raw_json = self._call_gemini(api_key, context_text)

        recommendations = self._parse_recommendations(raw_json)
        created = self._create_corrective_actions(recommendations)

        self.ai_recommendations_generated = True
        self.message_post(
            body=_(
                '<b>AI Corrective Action Recommendations</b><br/>'
                '%d recommended action(s) generated by AI and added to the '
                'Corrective Actions list for review.'
            ) % len(created),
            subtype_xmlid='mail.mt_note',
        )

        return {
            'type': 'ir.actions.client',
            'tag': 'incident_ai_reload',
            'params': {
                'res_id': self.id,
                'title': _('AI Recommendations Ready'),
                'message': _(
                    '%d corrective action(s) recommended by AI have been '
                    'added. Please review, assign responsible persons and due '
                    'dates before saving.'
                ) % len(created),
            },
        }

    # ── AI provider selection ───────────────────────────────────────────────
    def _get_ai_provider(self):
        """
        Determine which AI provider to use and return (provider, api_key).

        Priority order:
          1. Central AI app settings — ai.openai_key  → ('openai', key)
          2. Central AI app settings — ai.google_key  → ('google', key)
          3. Module-specific         — incident_management.openai_api_key
          4. Module-specific         — incident_management.google_api_key
        """
        params = self.env['ir.config_parameter'].sudo()

        key = params.get_param('ai.openai_key', default='')
        if key:
            return ('openai', key)

        key = params.get_param('ai.google_key', default='')
        if key:
            return ('google', key)

        key = params.get_param('incident_management.openai_api_key', default='')
        if key:
            return ('openai', key)

        key = params.get_param('incident_management.google_api_key', default='')
        if key:
            return ('google', key)

        raise UserError(_(
            'No AI API key has been configured.\n\n'
            'Please set one in:\n'
            '  • General Settings → AI (recommended), or\n'
            '  • Incidents → Configuration → AI Settings.'
        ))

    # ── Context builder ─────────────────────────────────────────────────────
    def _build_incident_context(self):
        rec = self

        # Categories
        categories = ', '.join(rec.incident_type_ids.mapped('name')) or 'Not specified'

        # Severity
        severity_map = {'low': 'Low', 'medium': 'Medium', 'high': 'High', 'critical': 'Critical'}
        severity = severity_map.get(rec.severity, rec.severity)

        # ICAM findings
        findings_text = ''
        if rec.finding_ids:
            lines = []
            for f in rec.finding_ids:
                cat = f.icam_category_id.name if f.icam_category_id else ''
                factor = f.icam_factor_id.name if f.icam_factor_id else ''
                root = ' [ROOT CAUSE]' if f.is_root_cause else ''
                lines.append(
                    f'  • [{cat}] {factor}{root}: {f.description or "(no detail)"}'
                )
            findings_text = '\n'.join(lines)
        else:
            findings_text = '  • No ICAM findings recorded yet.'

        # Injury body parts if applicable
        body_parts_text = ''
        if rec.is_injury and rec.injury_body_parts_display:
            body_parts_text = f'\nBody Parts Affected: {rec.injury_body_parts_display}'

        context = f"""INCIDENT REPORT SUMMARY
=======================
Reference:       {rec.name}
Date:            {rec.date_occurred.strftime('%d %b %Y %H:%M') if rec.date_occurred else 'Unknown'}
Location:        {rec.location or 'Unknown'}{(' — ' + rec.exact_location) if rec.exact_location else ''}
Categories:      {categories}
Severity:        {severity}
Person Type:     {dict(rec._fields['person_type'].selection).get(rec.person_type, rec.person_type)}
Near Miss:       {'Yes' if rec.near_miss else 'No'}{body_parts_text}

INCIDENT DESCRIPTION
--------------------
{rec.description or 'Not provided.'}

IMMEDIATE ACTIONS TAKEN
-----------------------
{rec.immediate_action_taken or 'None recorded.'}

IMMEDIATE CAUSE
---------------
{rec.immediate_cause_desc or 'Not yet determined.'}

ICAM FINDINGS
-------------
{findings_text}

INVESTIGATION CONCLUSION
------------------------
{rec.investigation_conclusion or 'Investigation not yet concluded.'}
"""
        return context.strip()

    # ── System prompt (shared by all providers) ─────────────────────────────
    @staticmethod
    def _system_prompt():
        return (
            'You are a workplace health and safety expert specialising in incident '
            'investigation and corrective action planning. You apply the Hierarchy of '
            'Controls framework:\n'
            '1. Eliminate – remove the hazard entirely\n'
            '2. Substitute – replace the hazard with a safer alternative\n'
            '3. Engineering Control – isolate people from the hazard\n'
            '4. Administrative Control – change the way people work\n'
            '5. PPE – protect the worker with personal protective equipment\n\n'
            'When given an incident summary you will recommend practical, specific '
            'corrective actions. You MUST return ONLY a valid JSON object — no prose, '
            'no markdown fences — in exactly this structure:\n\n'
            '{\n'
            '  "recommendations": [\n'
            '    {\n'
            '      "name": "Concise action description (max 120 chars)",\n'
            '      "action_type": "eliminate|substitute|engineering|administrative|ppe|other",\n'
            '      "priority": "0|1|2|3",\n'
            '      "rationale": "One or two sentences explaining why this action will prevent recurrence.",\n'
            '      "days_to_complete": <integer number of days from today>\n'
            '    }\n'
            '  ]\n'
            '}\n\n'
            'Priority values: 0=Normal, 1=Important, 2=Very Important, 3=Critical.\n'
            'Provide between 3 and 8 recommendations, ordered from highest to lowest '
            'priority in the Hierarchy of Controls (eliminate first, PPE last). Be '
            'specific — vague actions like "improve training" are not acceptable; instead '
            'say "Develop and deliver a 2-hour forklift pre-start inspection refresher '
            'course for all warehouse staff".'
        )

    # ── OpenAI API call ─────────────────────────────────────────────────────
    def _call_openai(self, api_key, context_text):
        """Call OpenAI Chat Completions API (gpt-4o) and return the response text."""
        url = 'https://api.openai.com/v1/chat/completions'
        payload = {
            'model': 'gpt-4o',
            'messages': [
                {'role': 'system', 'content': self._system_prompt()},
                {
                    'role': 'user',
                    'content': (
                        'Please analyse the following incident and recommend '
                        f'corrective actions:\n\n{context_text}'
                    ),
                },
            ],
            'max_tokens': 4096,
            'temperature': 0.3,
        }
        headers = {
            'Authorization': f'Bearer {api_key}',
            'Content-Type': 'application/json',
        }

        try:
            resp = requests.post(url, json=payload, headers=headers, timeout=60)
        except requests.exceptions.Timeout:
            raise UserError(_('The OpenAI API request timed out. Please try again.'))
        except requests.exceptions.ConnectionError:
            raise UserError(_(
                'Could not connect to the OpenAI API. '
                'Please check your internet connection.'
            ))

        if resp.status_code == 200:
            data = resp.json()
            try:
                return data['choices'][0]['message']['content']
            except (KeyError, IndexError):
                _logger.error('Unexpected OpenAI response format: %s', data)
                raise UserError(_(
                    'OpenAI returned an unexpected response format. Please try again.'
                ))

        try:
            detail = resp.json().get('error', {}).get('message', resp.text[:300])
        except Exception:
            detail = resp.text[:300]

        status = resp.status_code
        _logger.warning('OpenAI API returned %s: %s', status, detail)

        if status == 401:
            raise UserError(_(
                'The OpenAI API key is invalid or has been revoked. '
                'Please update it in the AI settings.'
            ))
        elif status == 429:
            raise UserError(_(
                'The OpenAI API rate limit has been reached. '
                'Please wait a moment and try again.'
            ))
        else:
            raise UserError(_('OpenAI API error (%s): %s') % (status, detail))

    # ── Gemini API call ─────────────────────────────────────────────────────
    def _call_gemini(self, api_key, context_text):
        """Call Google Gemini generateContent API and return the response text."""
        user_text = (
            'Please analyse the following incident and recommend '
            f'corrective actions:\n\n{context_text}'
        )
        payload = {
            'contents': [{'role': 'user', 'parts': [{'text': user_text}]}],
            'systemInstruction': {'parts': [{'text': self._system_prompt()}]},
            'generationConfig': {'temperature': 0.3, 'maxOutputTokens': 4096},
        }

        # Try gemini-2.5-flash first, fall back to gemini-1.5-flash
        for model in ('gemini-2.5-flash', 'gemini-1.5-flash'):
            url = (
                f'{GEMINI_BASE}/v1beta/models/{model}'
                f':generateContent?key={api_key}'
            )
            _logger.info('Gemini: trying model %s', model)
            try:
                resp = requests.post(url, json=payload, timeout=60)
            except requests.exceptions.Timeout:
                raise UserError(_('The Gemini API request timed out. Please try again.'))
            except requests.exceptions.ConnectionError:
                raise UserError(_(
                    'Could not connect to the Gemini API. '
                    'Please check your internet connection.'
                ))

            if resp.status_code == 200:
                data = resp.json()
                try:
                    return data['candidates'][0]['content']['parts'][0]['text']
                except (KeyError, IndexError):
                    _logger.error('Unexpected Gemini response format: %s', data)
                    raise UserError(_(
                        'Gemini returned an unexpected response format. Please try again.'
                    ))

            try:
                detail = resp.json().get('error', {}).get('message', resp.text[:300])
            except Exception:
                detail = resp.text[:300]

            status = resp.status_code
            _logger.warning('Gemini model %s returned %s: %s', model, status, detail)

            if status == 404:
                # Model not available for this key — try the next one
                continue
            elif status in (401, 403):
                raise UserError(_(
                    'The Google Gemini API key is invalid or access was denied. '
                    'Please update it in the AI settings.\n\n%s'
                ) % detail)
            elif status == 429:
                raise UserError(_(
                    'The Gemini API rate limit has been reached. '
                    'Please wait a moment and try again.'
                ))
            else:
                raise UserError(_('Gemini API error (%s): %s') % (status, detail))

        raise UserError(_(
            'No available Gemini model could be reached with your API key. '
            'Please verify your key at https://aistudio.google.com/apikey'
        ))

    # ── JSON parser ─────────────────────────────────────────────────────────
    def _parse_recommendations(self, raw_json):
        # Strip markdown fences if the model added them despite instructions
        text = raw_json.strip()
        if text.startswith('```'):
            text = text.split('\n', 1)[-1]
            if text.endswith('```'):
                text = text.rsplit('```', 1)[0]

        try:
            data = json.loads(text)
        except json.JSONDecodeError as e:
            _logger.error('Failed to parse AI JSON response: %s\n%s', e, raw_json)
            raise UserError(_(
                'The AI returned a response that could not be parsed as JSON. '
                'Please try again. If the problem persists, check the server logs.'
            ))

        recommendations = data.get('recommendations', [])
        if not recommendations:
            raise UserError(_(
                'The AI did not return any corrective action recommendations. '
                'Please try again.'
            ))

        # Validate and normalise each item
        valid_types = {'eliminate', 'substitute', 'engineering', 'administrative', 'ppe', 'other'}
        valid_priorities = {'0', '1', '2', '3'}
        normalised = []
        for item in recommendations:
            action_type = str(item.get('action_type', 'other')).lower()
            if action_type not in valid_types:
                action_type = 'other'
            priority = str(item.get('priority', '0'))
            if priority not in valid_priorities:
                priority = '0'
            days = int(item.get('days_to_complete', 30))
            normalised.append({
                'name': str(item.get('name', 'Review and correct hazard'))[:120],
                'action_type': action_type,
                'priority': priority,
                'rationale': str(item.get('rationale', '')),
                'days': max(1, days),
            })
        return normalised

    # ── Record creator ──────────────────────────────────────────────────────
    def _create_corrective_actions(self, recommendations):
        today = fields.Date.today()
        default_responsible = self.responsible_manager_id or self.env.user
        Action = self.env['incident.corrective.action']
        created = Action
        for rec in recommendations:
            notes = rec['rationale'] if rec['rationale'] else ''
            if notes:
                notes = f'[AI Generated]\n{notes}'
            else:
                notes = '[AI Generated]'
            action = Action.create({
                'incident_id': self.id,
                'name': rec['name'],
                'action_type': rec['action_type'],
                'priority': rec['priority'],
                'responsible_id': default_responsible.id,
                'due_date': today + timedelta(days=rec['days']),
                'notes': notes,
                'state': 'open',
            })
            created |= action
        return created
