# -*- coding: utf-8 -*-
{
    'name': 'Membership Management',
    'version': '19.0.1.1.0',
    'summary': 'Manage memberships, member cards, and instant check-in',
    'category': 'Membership',
    'author': "Cliff's Country Crafts",
    'website': '',
    'license': 'LGPL-3',
    'icon': 'membership_management/static/description/icon.png',
    'application': True,
    'depends': ['product', 'mail', 'base_setup'],
    'data': [
        'security/access_levels.xml',
        'security/ir.model.access.csv',
        'data/access_roles.xml',
        'data/res_lang_data.xml',
        'data/membership_sequence.xml',
        'data/membership_status_data.xml',
        'wizards/membership_letter_wizard_views.xml',
        'wizards/membership_email_wizard_views.xml',
        'reports/membership_card_actions.xml',
        'reports/membership_card_template.xml',
        'views/membership_status_views.xml',
        'views/membership_letter_template_views.xml',
        'views/membership_email_template_views.xml',
        'views/membership_views.xml',
        'views/product_template_views.xml',
        'views/membership_menus.xml',
    ],
    'installable': True,
}
