{
    'name': 'Injury Management',
    'version': '19.0.1.0.0',
    'summary': 'Return to Work case management',
    'description': 'Manage Return to Work cases including case notes, medical appointments, meetings, file notes, costs, RTW plans, and medical certificates.',
    'category': 'Human Resources',
    'author': 'Custom',
    'depends': ['mail', 'hr', 'incident_management'],
    'data': [
        'security/injury_security.xml',
        'security/ir.model.access.csv',
        'data/injury_sequence_data.xml',
        'data/res_lang_data.xml',
        'views/injury_rtw_case_views.xml',
        'views/injury_case_note_views.xml',
        'views/injury_medical_appointment_views.xml',
        'views/injury_meeting_views.xml',
        'views/injury_file_note_views.xml',
        'views/injury_cost_views.xml',
        'report/injury_rtw_plan_report.xml',
        'report/injury_case_report.xml',
        'views/injury_rtw_plan_views.xml',
        'views/injury_medical_certificate_views.xml',
        'views/injury_case_document_views.xml',
        'views/injury_case_report_wizard_views.xml',
        'views/incident_report_ext_views.xml',
        'views/injury_config_settings_views.xml',
        'views/injury_menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
