from . import kennel_options
from . import kennel_diet
from . import kennel_yard
from . import kennel_resident
from . import kennel_booking
from . import kennel_booking_line
from . import kennel_medication
from . import kennel_observation
from . import res_partner
