#!/usr/bin/env python3
"""Build the packaged classification and pictures for the schedule species.

Looks up every species in data/zoo_species_data.xml with the same code the
module uses at runtime (lib/taxonomy_lookup.py) and writes:

- static/species/<code>.jpg      picture (Wikipedia lead image), max 600px
- static/species/<code>_map.png  geographic distribution map, max 600px
- data/zoo_species_taxonomy_data.xml  the classification, reference URL and
  pictures for each species, loaded on install after the schedule.

Only what was found is written; species with nothing found are left for the
module's own background lookup. Results are cached in a JSON file so the
script can be stopped and resumed.

Usage (needs requests, lxml and Pillow, e.g. an Odoo virtualenv):
    python tools/build_species_data.py [--cache /tmp/species_cache.json]
"""
import argparse
import base64
import importlib.util
import io
import json
import os
import time
from xml.sax.saxutils import escape

from lxml import etree
from PIL import Image

MODULE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIELDS = {'kingdom': 'taxon_kingdom', 'phylum': 'taxon_phylum', 'class': 'taxon_class', 'order': 'taxon_order',
          'family': 'taxon_family', 'genus': 'taxon_genus', 'species': 'taxon_species'}
MAX_SIZE = 600


def load_lookup():
    spec = importlib.util.spec_from_file_location('taxonomy_lookup', os.path.join(MODULE, 'lib', 'taxonomy_lookup.py'))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def schedule_species():
    tree = etree.parse(os.path.join(MODULE, 'data', 'zoo_species_data.xml'))
    for record in tree.iter('record'):
        if record.get('model') == 'zoo.species':
            values = {f.get('name'): (f.text or '') for f in record.iter('field')}
            yield record.get('id'), values['species_code'], values['scientific_name']


def save_picture(b64, path, fmt):
    image = Image.open(io.BytesIO(base64.b64decode(b64)))
    image.thumbnail((MAX_SIZE, MAX_SIZE))
    if fmt == 'JPEG' and image.mode not in ('RGB', 'L'):
        image = image.convert('RGB')
    image.save(path, fmt, optimize=True, **({'quality': 85} if fmt == 'JPEG' else {}))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--cache', default=os.path.join(MODULE, 'tools', '.species_cache.json'))
    args = parser.parse_args()
    lookup = load_lookup()
    cache = json.load(open(args.cache)) if os.path.exists(args.cache) else {}
    pictures_dir = os.path.join(MODULE, 'static', 'species')
    os.makedirs(pictures_dir, exist_ok=True)

    species = list(schedule_species())
    for n, (xml_id, code, name) in enumerate(species, 1):
        if code in cache:
            continue
        entry = {'name': name}
        try:
            entry['taxa'] = lookup.lookup_classification(name)
            found = lookup.lookup_images(name)
            entry['url'] = found.get('url')
            if found.get('image'):
                save_picture(found['image'], os.path.join(pictures_dir, f'{code}.jpg'), 'JPEG')
                entry['image'] = True
            if found.get('distribution'):
                save_picture(found['distribution'], os.path.join(pictures_dir, f'{code}_map.png'), 'PNG')
                entry['map'] = True
        except Exception as error:  # noqa: BLE001 - record and move on; rerun to retry
            print(f'{n}/{len(species)} {code} {name}: FAILED {error}')
            continue
        cache[code] = entry
        json.dump(cache, open(args.cache, 'w'), indent=1)
        print(f"{n}/{len(species)} {code} {name}: {len(entry['taxa'])} ranks, "
              f"image={'y' if entry.get('image') else 'n'} map={'y' if entry.get('map') else 'n'}")
        time.sleep(0.3)  # be polite to GBIF and Wikipedia

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by tools/build_species_data.py: scientific classification (GBIF',
        '     Backbone Taxonomy, exact matches only) and pictures (English Wikipedia)',
        '     for the schedule species. noupdate so later edits are kept. -->',
        '<odoo noupdate="1">',
    ]
    for xml_id, code, name in species:
        entry = cache.get(code)
        if not entry:
            continue
        fields = [f'        <field name="{FIELDS[rank]}">{escape(value)}</field>'
                  for rank, value in entry['taxa'].items() if rank in FIELDS]
        if entry.get('url'):
            fields.append(f'        <field name="reference_url">{escape(entry["url"])}</field>')
        if entry.get('image'):
            fields.append(f'        <field name="image" type="base64" file="zoo_manager/static/species/{code}.jpg"/>')
        if entry.get('map'):
            fields.append(f'        <field name="distribution_image" type="base64" file="zoo_manager/static/species/{code}_map.png"/>')
        if not fields:
            continue
        complete = len(entry['taxa']) == len(FIELDS) and entry.get('image') and entry.get('map')
        fields.append(f'        <field name="lookup_pending" eval="{not complete}"/>')
        lines += [f'    <record id="{xml_id}" model="zoo.species">', *fields, '    </record>']
    lines.append('</odoo>\n')
    with open(os.path.join(MODULE, 'data', 'zoo_species_taxonomy_data.xml'), 'w') as out:
        out.write('\n'.join(lines))
    print('Wrote data/zoo_species_taxonomy_data.xml for', sum(1 for c in cache if cache[c]), 'species')


if __name__ == '__main__':
    main()
