# -*- coding: utf-8 -*-
{
    'name': 'Asset Management',
    'version': '19.0.1.0.0',
    'category': 'Operations/Assets',
    'summary': 'Track physical assets with usage logs, defect reports, maintenance history and a mobile-first PWA control plane.',
    'author': 'Custom',
    'depends': ['base', 'mail', 'hr'],
    'data': [
        'security/asset_security.xml',
        'security/ir.model.access.csv',
        'data/res_lang_data.xml',
        'data/asset_sequence.xml',
        'data/asset_maintenance_type_data.xml',
        'data/asset_defect_severity_data.xml',
        'views/asset_usage_unit_views.xml',
        'views/asset_type_views.xml',
        'views/asset_subtype_views.xml',
        'views/asset_maintenance_type_views.xml',
        'views/asset_defect_severity_views.xml',
        'views/asset_asset_views.xml',
        'views/asset_usage_log_views.xml',
        'views/asset_defect_views.xml',
        'views/asset_maintenance_log_views.xml',
        'views/asset_location_log_views.xml',
        'views/asset_menus.xml',
        'templates/asset_cp_templates.xml',
        'templates/asset_report_cp.xml',
    ],
    'assets': {
        'web.assets_frontend': [],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
