#!/usr/bin/env python3
"""Generate a module's access level security files from its access_levels.py.

    python3 tools/generate_access_levels.py <module> [<module> ...]

Writes, for each module:

* security/access_levels.xml - category (when the module owns it), one privilege per
  model with View Only / Create / Create and Edit Own Only / Update / Delete groups,
  the Create and Edit Own Only record rules, and full access for the admin user.
* security/ir.model.access.csv - access rows for those groups, read access to CONFIG
  models for internal users, and the module's EXTRA_ACCESS rows.
* data/access_roles.xml - refreshes the Permission Management role library on every
  install/upgrade (does nothing when permission_management is not installed).

See permission_management/access_levels_lib.py for the access_levels.py format.
"""
import importlib.util
import os
import sys
from xml.sax.saxutils import escape

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


lib = _load(os.path.join(ROOT, 'permission_management', 'access_levels_lib.py'), 'access_levels_lib')


def model_entries(model):
    """[(model_xmlid, own_fields)] for a MODELS entry."""
    xmlids = model[3]
    if isinstance(xmlids, dict):
        return list(xmlids.items())
    return [(xmlid, model[4] if index == 0 else []) for index, xmlid in enumerate(xmlids)]


def own_domain(own_fields):
    fields = [] if '-create_uid' in own_fields else ['create_uid']
    fields += [field for field in own_fields if field not in ('create_uid', '-create_uid')]
    terms = ["('%s', 'in', [user.id])" % field for field in fields]
    return '[%s%s]' % ("'|', " * (len(terms) - 1), ', '.join(terms))


def generate_security_xml(spec):
    prefix = spec.PREFIX
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/generate_access_levels.py from access_levels.py - edit that',
           '     file and re-run the generator rather than editing this one. -->',
           '<odoo>']
    if '.' not in spec.CATEGORY:
        out += ['    <record id="%s" model="ir.module.category">' % spec.CATEGORY,
                '        <field name="name">%s</field>' % escape(spec.APP_NAME),
                '    </record>']
    for sequence, model in enumerate(spec.MODELS, 1):
        key, label = model[0], model[1]
        privilege = 'privilege_%s_%s' % (prefix, key)
        out += ['',
                '    <!-- %s -->' % escape(label),
                '    <record id="%s" model="res.groups.privilege">' % privilege,
                '        <field name="name">%s</field>' % escape(label),
                '        <field name="category_id" ref="%s"/>' % spec.CATEGORY,
                '        <field name="sequence">%d</field>' % (sequence * 10),
                '    </record>']
        for perm_sequence, permission in enumerate(lib.PERMISSIONS, 1):
            group = 'group_%s_%s_%s' % (prefix, key, permission)
            out += ['    <record id="%s" model="res.groups">' % group,
                    '        <field name="name">%s</field>' % lib.PERMISSION_LABELS[permission],
                    '        <field name="privilege_id" ref="%s"/>' % privilege,
                    '        <field name="sequence">%d</field>' % (perm_sequence * 10)]
            if permission != 'view':
                out.append('        <field name="implied_ids" eval="[(4, ref(\'group_%s_%s_view\'))]"/>'
                           % (prefix, key))
            out.append('    </record>')
        override = "[(4, ref('group_%s_%s_update')), (4, ref('group_%s_%s_delete'))]" % (
            prefix, key, prefix, key)
        for model_xmlid, own_fields in model_entries(model):
            rule = 'rule_' + model_xmlid.split('.')[-1][len('model_'):]
            out += ['    <record id="%s_own_only" model="ir.rule">' % rule,
                    '        <field name="name">%s: Create and Edit Own Only</field>' % escape(label),
                    '        <field name="model_id" ref="%s"/>' % model_xmlid,
                    '        <field name="groups" eval="[(4, ref(\'group_%s_%s_own\'))]"/>' % (prefix, key),
                    '        <field name="domain_force">%s</field>' % escape(own_domain(own_fields)),
                    '    </record>',
                    '    <record id="%s_all_records" model="ir.rule">' % rule,
                    '        <field name="name">%s: any record (Update or Delete)</field>' % escape(label),
                    '        <field name="model_id" ref="%s"/>' % model_xmlid,
                    '        <field name="groups" eval="%s"/>' % override,
                    '        <field name="domain_force">[(1, \'=\', 1)]</field>',
                    '    </record>']
    admin_groups = ',\n            '.join(
        "(4, ref('group_%s_%s_%s'))" % (prefix, model[0], permission)
        for model in spec.MODELS for permission in ('view', 'create', 'update', 'delete'))
    out += ['',
            '    <!-- The database administrator gets full access on install and every upgrade. -->',
            '    <record id="base.user_admin" model="res.users">',
            '        <field name="group_ids" eval="[',
            '            %s,' % admin_groups,
            '        ]"/>',
            '    </record>',
            '</odoo>']
    return '\n'.join(out) + '\n'


def generate_access_csv(spec):
    rows = ['id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink']
    for model in spec.MODELS:
        key, kind = model[0], model[2]
        for model_xmlid, _own in model_entries(model):
            short = model_xmlid.split('.')[-1][len('model_'):]
            for permission in lib.PERMISSIONS:
                rows.append('access_%s_%s,%s %s,%s,group_%s_%s_%s,%s' % (
                    short, permission, short.replace('_', '.'), permission, model_xmlid,
                    spec.PREFIX, key, permission, lib.PERMISSION_ACCESS[permission]))
            if kind == lib.CONFIG:
                rows.append('access_%s_internal_read,%s internal read,%s,base.group_user,1,0,0,0' % (
                    short, short.replace('_', '.'), model_xmlid))
    for access_id, model_xmlid, group, perms in getattr(spec, 'EXTRA_ACCESS', []):
        flags = ','.join('1' if flag in perms else '0' for flag in 'rwcu')
        rows.append('%s,%s,%s,%s,%s' % (access_id, access_id, model_xmlid, group, flags))
    return '\n'.join(rows) + '\n'


def generate_roles_xml(module, spec):
    return '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_access_levels.py. Not noupdate, so it runs on every
     install/upgrade: adds this app's roles (from access_levels.py) to the Permission
     Management role library. Does nothing when permission_management is not installed;
     roles that already exist are left as they are. -->
<odoo>
    <record id="action_sync_permission_roles" model="ir.actions.server">
        <field name="name">%s: Sync Permission Management Roles</field>
        <field name="model_id" ref="base.model_ir_module_module"/>
        <field name="state">code</field>
        <field name="code">if 'permission.role' in env:
    env['permission.role']._load_role_library()</field>
    </record>
    <function model="ir.actions.server" name="run" eval="[ref('action_sync_permission_roles')]"/>
</odoo>
''' % escape(spec.APP_NAME)


def main(modules):
    for module in modules:
        path = os.path.join(ROOT, module)
        spec = _load(os.path.join(path, 'access_levels.py'), '%s_access_levels' % module)
        for rel, content in (
            ('security/access_levels.xml', generate_security_xml(spec)),
            ('security/ir.model.access.csv', generate_access_csv(spec)),
            ('data/access_roles.xml', generate_roles_xml(module, spec)),
        ):
            os.makedirs(os.path.join(path, os.path.dirname(rel)), exist_ok=True)
            with open(os.path.join(path, rel), 'w') as handle:
                handle.write(content)
        print('%s: %d models, %d roles' % (module, len(spec.MODELS), len(lib.module_roles(spec))))


if __name__ == '__main__':
    main(sys.argv[1:])
