from . import org_division
from . import org_business_unit
from . import org_location
from . import org_department
from . import org_scope_mixin
from . import base
from . import ir_model_fields
from . import res_users_org_scope
from . import res_users
from . import ir_rule
from . import ir_ui_menu
